# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[9, 1, 4, 1, 6, 3, 3, 6, 9, 6, 9, 9],
       [9, 8, 4, 8, 4, 9, 7, 6, 5, 2, 1, 1],
       [6, 8, 5, 4, 8, 6, 6, 3, 3, 2, 9, 7],
       [6, 8, 3, 2, 2, 1, 2, 0, 8, 2, 6, 3],
       [8, 7, 5, 0, 6, 7, 5, 2, 0, 6, 8, 7],
       [9, 6, 8, 3, 9, 9, 1, 9, 3, 7, 0, 4],
       [7, 7, 9, 0, 0, 5, 9, 7, 9, 1, 3, 2],
       [4, 8, 1, 5, 4, 2, 8, 0, 9, 9, 3, 5],
       [3, 8, 0, 2, 6, 4, 7, 9, 0, 6, 8, 3],
       [7, 3, 8, 7, 1, 2, 6, 5, 0, 8, 2, 4],
       [4, 4, 4, 4, 9, 9, 0, 8, 6, 9, 4, 6],
       [4, 0, 8, 2, 1, 2, 9, 9, 8, 9, 9, 6]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[9, 1, 4, 1, 6, 3, 3, 6, 9, 6, 9, 9],
       [9, 8, 4, 8, 4, 9, 7, 6, 5, 2, 1, 1],
       [6, 8, 5, 4, 8, 6, 6, 3, 3, 2, 9, 7],
       [6, 8, 3, 2, 2, 1, 2, 0, 8, 2, 6, 3],
       [8, 7, 5, 0, 6, 7, 5, 2, 0, 6, 8, 7],
       [9, 6, 8, 3, 9, 9, 1, 9, 3, 7, 0, 4],
       [7, 7, 9, 0, 0, 5, 9, 7, 9, 1, 3, 2],
       [4, 8, 1, 5, 4, 2, 8, 0, 9, 9, 3, 5],
       [3, 8, 0, 2, 6, 4, 7, 9, 0, 6, 8, 3],
       [7, 3, 8, 7, 1, 2, 6, 5, 0, 8, 2, 4],
       [4, 4, 4, 4, 9, 9, 0, 8, 6, 9, 4, 6],
       [4, 0, 8, 2, 1, 2, 9, 9, 8, 9, 9, 6]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  10,  -9,  19, -15,  16,   4,   3,   0,  -6, -17,   0],
       [  0,   5,   1,  -7,  16,   0,   6,  -3,  -6,  -8,  20,   0],
       [  0,   8,  -8,  -1,  -9, -13,  -4, -15,  27, -14,   2,   0],
       [  0,   1,   2, -16,   6,   7,   8,  -6, -19,   7,  13,   0],
       [  0,  -7,   9,  -5,  18,  14, -28,  23, -13,  18, -22,   0],
       [  0,  -2,  20, -17, -18,   0,  15,   1,  16, -24,   6,   0],
       [  0,  12, -18,  13,   3, -13,  14, -33,  18,  17, -13,   0],
       [  0,  18, -19, -10,  13,  -1,   1,  24, -24,  -1,  18,   0],
       [  0, -15,  18,  13, -20, -12,  10,  -3, -19,  15, -16,   0],
       [  0,   5,  -8,  -6,  21,  23, -32,  12,  -1,   9, -10,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()